import { useEffect } from 'react';
import { motion } from 'framer-motion';
import confetti from 'canvas-confetti';
import { 
  Award, 
  Download, 
  ArrowLeft, 
  CheckCircle2, 
  AlertTriangle, 
  TrendingUp, 
  Sparkles, 
  HelpCircle, 
  Briefcase,
  Check,
  X,
  Plus,
  Compass,
  FileSpreadsheet
} from 'lucide-react';
import MetricCard from './MetricCard';
import SkillChips from './SkillChips';
import GaugeChart from './GaugeChart';
import TiltCard from './TiltCard';

function parseList(value) {
  if (!value) return [];
  if (Array.isArray(value)) return value.map(String).filter(Boolean);
  if (typeof value === 'string') {
    const trimmed = value.trim();
    if (trimmed.startsWith('[') && trimmed.endsWith(']')) {
      try {
        const parsed = JSON.parse(trimmed);
        if (Array.isArray(parsed)) return parsed.map(String).filter(Boolean);
      } catch (e) {}
    }
    return trimmed.split(',').map((s) => s.trim()).filter((s) => s.length > 1);
  }
  return [];
}

function getBadge(pct) {
  if (pct >= 80) return <span className="badge badge-success">✓ Strong Match</span>;
  if (pct >= 60) return <span className="badge badge-warning">◐ Moderate Match</span>;
  return <span className="badge badge-danger">✕ Needs Optimization</span>;
}

const stagger = {
  hidden: {},
  show: { transition: { staggerChildren: 0.1 } },
};

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.16, 1, 0.3, 1] } },
};

export default function ResultsPanel({ result, onBack }) {
  if (!result) return null;

  const pct = Number(result.overall_match_percentage) || 0;
  const matched      = parseList(result.skills_matched);
  const missing      = parseList(result.skills_missing);
  const extra        = parseList(result.skills_extra);
  const strengths    = parseList(result.strength_areas);
  const improvements = parseList(result.improvement_areas);
  const recs         = parseList(result.specific_recommendations);
  const interview    = parseList(result.interview_preparation);

  // Trigger high-end celebration confetti burst on mount
  useEffect(() => {
    try {
      // First wave
      confetti({
        particleCount: 80,
        spread: 70,
        origin: { y: 0.6 },
        colors: ['#4f46e5', '#06b6d4', '#ec4899', '#10b981', '#f59e0b'],
      });

      // Second burst
      const timer = setTimeout(() => {
        confetti({
          particleCount: 50,
          angle: 60,
          spread: 55,
          origin: { x: 0 },
          colors: ['#4f46e5', '#06b6d4', '#10b981'],
        });
        confetti({
          particleCount: 50,
          angle: 120,
          spread: 55,
          origin: { x: 1 },
          colors: ['#ec4899', '#f59e0b', '#7c3aed'],
        });
      }, 350);

      return () => clearTimeout(timer);
    } catch {
      // Ignore if canvas-confetti is not supported
    }
  }, []);

  function handleExport() {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `resume_match_analysis_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <motion.div variants={stagger} initial="hidden" animate="show">
      {/* Top Header */}
      <motion.div variants={fadeUp} className="results-header">
        <div>
          <span className="results-title">AI Skill Gap Audit</span>
          <p style={{ color: 'var(--text-3)', fontSize: '0.9rem', marginTop: 4 }}>
            Deep analysis generated by Groq LLM
          </p>
        </div>

        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ delay: 0.2, type: 'spring', stiffness: 400, damping: 15 }}
        >
          {getBadge(pct)}
        </motion.div>
      </motion.div>

      {/* 4 Metric Cards */}
      <div className="metrics-row">
        <MetricCard label="Matched Skills" value={matched.length} delay={0.1} />
        <MetricCard label="Missing Skills" value={missing.length} color="var(--danger)" delay={0.18} />
        <MetricCard label="Extra Skills" value={extra.length} color="var(--warning)" delay={0.26} />
        <MetricCard label="Match Score" value={`${pct}%`} delay={0.34} />
      </div>

      {/* Gauge & Assessment Breakdown */}
      <motion.div variants={fadeUp} className="grid-2 mb-24">
        <TiltCard>
          <div className="sec-title">Overall Alignment</div>
          <div className="card-sub">Quantitative resume match percentage</div>
          <GaugeChart percentage={pct} />
        </TiltCard>

        <TiltCard>
          <div className="sec-title">Executive Assessment</div>
          <div className="card-sub">ATS compatibility and selection probability</div>

          <div className="assess-row">
            <span className="assess-key">Selection Probability</span>
            <span className="assess-val" style={{ color: 'var(--primary)' }}>
              {result.selection_probability || 'High Probability'}
            </span>
          </div>
          <div className="assess-row">
            <span className="assess-key">Experience Depth Match</span>
            <span className="assess-val">{result.experience_match || 'Aligned'}</span>
          </div>
          <div className="assess-row">
            <span className="assess-key">Education &amp; Background</span>
            <span className="assess-val">{result.education_match || 'Meets criteria'}</span>
          </div>
          {result.salary_competitiveness && (
            <div className="assess-row">
              <span className="assess-key">Salary Range Position</span>
              <span className="assess-val">{result.salary_competitiveness}</span>
            </div>
          )}
        </TiltCard>
      </motion.div>

      {/* Skills Breakdown */}
      <motion.div variants={fadeUp} className="mb-24">
        <TiltCard>
          <div className="sec-title">Skills Breakdown Matrix</div>
          <div className="card-sub">Granular catalog of matched competencies, missing prerequisites, and bonus skills</div>

          <div className="skill-group">
            <div className="skill-group-label">
              <span style={{ color: '#059669', display: 'flex', alignItems: 'center' }}><Check size={16} /></span>
              <span>Matched Skills</span>
              <span className="skill-group-count">{matched.length}</span>
            </div>
            <SkillChips skills={matched} type="matched" />
          </div>

          <div className="skill-group">
            <div className="skill-group-label">
              <span style={{ color: '#e11d48', display: 'flex', alignItems: 'center' }}><X size={16} /></span>
              <span>Missing High-Priority Skills</span>
              <span className="skill-group-count">{missing.length}</span>
            </div>
            <SkillChips skills={missing} type="missing" />
          </div>

          <div className="skill-group">
            <div className="skill-group-label">
              <span style={{ color: '#d97706', display: 'flex', alignItems: 'center' }}><Plus size={16} /></span>
              <span>Additional &amp; Transferable Skills</span>
              <span className="skill-group-count">{extra.length}</span>
            </div>
            <SkillChips skills={extra} type="extra" />
          </div>
        </TiltCard>
      </motion.div>

      {/* Strengths & Improvement Areas */}
      <motion.div variants={fadeUp} className="grid-2 mb-24">
        <TiltCard>
          <div className="sec-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <Sparkles size={18} style={{ color: 'var(--primary)' }} />
            <span>Key Strengths Identified</span>
          </div>
          <div className="card-sub">What makes your application stand out</div>

          <div className="num-list">
            {strengths.map((s, i) => (
              <motion.div
                key={i}
                className="num-item"
                initial={{ opacity: 0, x: -14 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.4 + i * 0.08 }}
              >
                <span className="num-badge">{i + 1}</span>
                <span>{s}</span>
              </motion.div>
            ))}
          </div>
        </TiltCard>

        <TiltCard>
          <div className="sec-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <AlertTriangle size={18} style={{ color: 'var(--accent-rose)' }} />
            <span>Improvement Opportunities</span>
          </div>
          <div className="card-sub">Where to optimize your resume bullets</div>

          <div className="num-list">
            {improvements.map((s, i) => (
              <motion.div
                key={i}
                className="num-item"
                initial={{ opacity: 0, x: -14 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.4 + i * 0.08 }}
              >
                <span className="num-badge">{i + 1}</span>
                <span>{s}</span>
              </motion.div>
            ))}
          </div>
        </TiltCard>
      </motion.div>

      {/* Actionable Recommendations */}
      {recs.length > 0 && (
        <motion.div variants={fadeUp} className="mb-24">
          <TiltCard>
            <div className="sec-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <TrendingUp size={18} style={{ color: 'var(--primary)' }} />
              <span>Prioritized Next Action Roadmap</span>
            </div>
            <div className="card-sub">Tactical changes to maximize interview callback rates</div>

            <div className="rec-list">
              {recs.map((r, i) => (
                <motion.div
                  key={i}
                  className="rec-item"
                  initial={{ opacity: 0, x: -16 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.5 + i * 0.08 }}
                >
                  <span className="rec-num">{i + 1}</span>
                  <span>{r}</span>
                </motion.div>
              ))}
            </div>
          </TiltCard>
        </motion.div>
      )}

      {/* Interview Prep Questions */}
      {interview.length > 0 && (
        <motion.div variants={fadeUp} className="mb-24">
          <TiltCard>
            <div className="sec-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <HelpCircle size={18} style={{ color: 'var(--accent-cyan)' }} />
              <span>Tailored Interview Preparation Prompts</span>
            </div>
            <div className="card-sub">Likely technical and situational questions based on detected gaps</div>

            <div className="num-list">
              {interview.map((s, i) => (
                <motion.div
                  key={i}
                  className="num-item"
                  initial={{ opacity: 0, x: -14 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.6 + i * 0.08 }}
                >
                  <span className="num-badge">{i + 1}</span>
                  <span>{s}</span>
                </motion.div>
              ))}
            </div>
          </TiltCard>
        </motion.div>
      )}

      {/* Navigation Actions */}
      <motion.div variants={fadeUp} className="results-actions">
        <motion.button
          className="btn-outline"
          onClick={onBack}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
        >
          <ArrowLeft size={16} />
          <span>New Analysis</span>
        </motion.button>

        <motion.button
          className="btn-outline"
          onClick={handleExport}
          whileHover={{ scale: 1.02 }}
          whileTap={{ scale: 0.98 }}
          style={{ background: 'var(--bg-subtle)' }}
        >
          <Download size={16} />
          <span>Export JSON Report</span>
        </motion.button>
      </motion.div>
    </motion.div>
  );
}
